### PR TITLE
Development

### PR DESCRIPTION
**Pull request by entopia**
First Review Instructions

There is a lot of visual code to be reviewed. The best option would be to open "Protein Generator.gh" in Grasshopper and open all the different modules from there (with double clicking), to see the order of all the clusters. 
However, some modules that can be reviewed separately are exported, such as the little python modules in "Python Exports" and the python modules in the main view. Some very tiny python modules that are used for loops, or selections, are embedded in the main module or cluster and are not exported as they do not require reviewing. 

GH Modules that can be reviewed separately are exported as "clusters". You can open those in Grasshopper. those are independent input-output components. 

NOTE: PLUGIN HUMAN-UI WHICH IS USED FOR THE INTERFACE (SLIDERS) IS NOT WORKING FOR MAC.

### CODE REVIEW

**Comment by entopia** [comment]
Update:

Please only review the clashes.py module.

**Review by myyong — COMMENTED** [review]
1. Good docstrings. Clarify module purpose: Not to calculate energy clashes.
2. Doc strings for each function
3. SplitCoordinates to return list of coordinates instead of modifying global variables
4. Optimise for checking clashes (line 36),
```Python
for j in range (i+1, len(CA_xyz)):
```
should check only the amino acids following i+1. Can remove `if (i != j)`
5. Where is clash_th defined?
6. Extract dist measurement as a function
7. CheckClash should refer to xyz, not CA_xyz?
8. Should CheckClash return index/coordinates of BOTH clashing beads?
9. Line 43: What is `print clash`?
10. What's Error1?

**Comment by tannerox** [comment]
Good afternoon,
I’m not sure how I was put on this for sharing.  I don’t have anything to do with 
the project and have tried to unsubscribe but keep  getting alerts daily from 
GitHub for various turing projects.  Please look into this for me as it is 
really getting to be a lot of spam to clear out of my email box.
Thanks,
Jared

-------
Jared Tanner
Professor of the Mathematics of Information
Oxford University Liaison Director to the Alan Turing Institute
Mathematics Institute
University of Oxford
01865615311 (office - Andrew Wiles Building S2.40)
07981791786 (cell)
http://people.maths.ox.ac.uk/tanner

**Comment by entopia** [comment]
> 1. Good docstrings. Clarify module purpose: Not to calculate energy clashes.  - [ x]
> 2. Doc strings for each function - [ x]
> 3. SplitCoordinates to return list of coordinates instead of modifying global variables - [ x]
> 4. Optimise for checking clashes (line 36), - [ x]
> 
> ```python
> for j in range (i+1, len(CA_xyz)):
> ```
> 
> should check only the amino acids following i+1. Can remove `if (i != j)` 
> 5. Not sure how this code can run. Where is clash_th defined? #its a grasshopper input, usually these are not defined, but added it for module comprehension purposes. - [ x]
> 6. Extract dist measurement as a function - [ x]
> 7. CA_xyz not defined in CheckClash. Should it refer to xyz, not CA_xyz? - [ x]
> 8. Should CheckClash return index/coordinates of BOTH clashing beads? - [ x]
> 9. Line 43: What is `print clash`? removed - [ x]
> 10. What's Error1? produces GH error in the module renamed - [ ]

**Pull request merged**
